### ISSUE TITLE
sendMessage Looping Issue

### ISSUE THREAD

**Issue by udithishara** [DrMikeyS/FacebookBotPHP#1]
Hey,

I'm using the code provided, but it seem to loop, only way to stop the loop is comment out "sendMessage" call

`facebookBot::sendMessage($recievedMessageSender, "Hey, thanks for getting in touch");`

I've tried exit(), die(), break after "return $json;" but it still loops

![image](https://cloud.githubusercontent.com/assets/3581708/14854314/e9ed1db0-0cac-11e6-9875-65ec1df057ab.png)

**Comment by DrMikeyS** [comment]
Try:

```
$recievedMessage = facebookBot::getMessage();
$recievedMessageSender =  facebookBot::getSender();

//Send a simple response
if(recievedMessage){
   facebookBot::sendMessage($recievedMessageSender, "Hey, thanks for getting in touch");
}

I'll correct the class later - thanks for the bug report
```

**Comment by udithishara** [comment]
Yep, this works

Thanks for replying so quickly :)
